# User
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_COLOR=cyan

# Host
SPACESHIP_HOST_SHOW=always
SPACESHIP_HOST_PREFIX="@ "
SPACESHIP_HOST_COLOR=green
SPACESHIP_HOST_COLOR_SSH=red

# Dir
SPACESHIP_DIR_SHOW=true
SPACESHIP_DIR_PREFIX=": "
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_DIR_COLOR=yellow

# Char
SPACESHIP_CHAR_SYMBOL=">"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_COLOR_SUCCESS=red
SPACESHIP_CHAR_COLOR_FAILURE=red

# Exit Code
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_PREFIX=""

# Exec Time
SPACESHIP_EXEC_TIME_SHOW=true
SPACESHIP_EXEC_TIME_PREFIX=""
SPACESHIP_EXEC_TIME_ELAPSED=0

# Azure
SPACESHIP_AZURE_SHOW=true
SPACESHIP_AZURE_PREFIX=""
SPACESHIP_AZURE_SYMBOL=""
SPACESHIP_AZURE_COLOR=cyan

# Kubectl
SPACESHIP_KUBECTL_SHOW=true
SPACESHIP_KUBECTL_PREFIX=""

SPACESHIP_PROMPT_ORDER=(
    user
    host
    dir
    git
    line_sep
    char
)

SPACESHIP_RPROMPT_ORDER=(
    exit_code
    exec_time
    azure
    kubectl
)

