---
- name: Install packages (Ubuntu/Debian)
  become: true
  ansible.builtin.apt:
    name:
      - zsh
      - git
      - curl
      - wget
      - vim
      - ripgrep
      - make
      - cmake
      - gcc
      - socat
      - bat
      - tmux
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install packages (Arch)
  become: true
  community.general.pacman:
    name:
      - zsh
      - git
      - curl
      - wget
      - vim
      - ripgrep
      - make
      - cmake
      - gcc
      - socat
      - bat
      - tmux
    state: present
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install packages (macOS)
  community.general.homebrew:
    name:
      - zsh
      - git
      - curl
      - wget
      - vim
      - ripgrep
      - make
      - cmake
      - gcc
      - socat
      - bat
      - neovim
    state: present
  when: ansible_facts['os_family'] == "Darwin"
