---
- name: Install dotfiles
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    dotfiles_dir: "{{ playbook_dir | dirname }}"
    local_dir: "{{ ansible_env.HOME }}/.local"

  roles:
    - packages
    - neovim
    - fzf
    - spaceship
    - zsh-syntax-highlighting
    - symlinks
